<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Delatlantik\RichFormSymfonyBundle\Form\InputTypeExtension' shared service.

return $this->privates['Delatlantik\RichFormSymfonyBundle\Form\InputTypeExtension'] = new \Delatlantik\RichFormSymfonyBundle\Form\InputTypeExtension();
