<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'translator.selector' shared service.

return $this->privates['translator.selector'] = new \Symfony\Component\Translation\MessageSelector();
