<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'validator.builder' shared service.

$this->privates['validator.builder'] = $instance = \Symfony\Component\Validator\Validation::createValidatorBuilder();

$instance->setConstraintValidatorFactory(($this->privates['validator.validator_factory'] ?? $this->load('getValidator_ValidatorFactoryService.php')));
$instance->setTranslator(($this->services['translator'] ?? $this->load('getTranslatorService.php')));
$instance->setTranslationDomain('validators');
$instance->addXmlMappings(array(0 => ($this->targetDirs[4].'\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Form/Resources/config/validation.xml')));
$instance->addMethodMapping('loadValidatorMetadata');
$instance->addObjectInitializers(array());

return $instance;
