<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3H807Js\AppTestDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3H807Js/AppTestDebugProjectContainer.php') {
    touch(__DIR__.'/Container3H807Js.legacy');

    return;
}

if (!\class_exists(AppTestDebugProjectContainer::class, false)) {
    \class_alias(\Container3H807Js\AppTestDebugProjectContainer::class, AppTestDebugProjectContainer::class, false);
}

return new \Container3H807Js\AppTestDebugProjectContainer(array(
    'container.build_hash' => '3H807Js',
    'container.build_id' => '3c21b2f1',
    'container.build_time' => 1532009276,
), __DIR__.\DIRECTORY_SEPARATOR.'Container3H807Js');
