<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPDlbcwH\AppTestDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPDlbcwH/AppTestDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerPDlbcwH.legacy');

    return;
}

if (!\class_exists(AppTestDebugProjectContainer::class, false)) {
    \class_alias(\ContainerPDlbcwH\AppTestDebugProjectContainer::class, AppTestDebugProjectContainer::class, false);
}

return new \ContainerPDlbcwH\AppTestDebugProjectContainer(array(
    'container.build_hash' => 'PDlbcwH',
    'container.build_id' => '6e719c46',
    'container.build_time' => 1531740164,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerPDlbcwH');
