<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFVsGT4k\AppTestDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFVsGT4k/AppTestDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerFVsGT4k.legacy');

    return;
}

if (!\class_exists(AppTestDebugProjectContainer::class, false)) {
    \class_alias(\ContainerFVsGT4k\AppTestDebugProjectContainer::class, AppTestDebugProjectContainer::class, false);
}

return new \ContainerFVsGT4k\AppTestDebugProjectContainer(array(
    'container.build_hash' => 'FVsGT4k',
    'container.build_id' => 'dafcf651',
    'container.build_time' => 1531913425,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerFVsGT4k');
